# Generated by Django 5.0.3 on 2024-03-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='dni',
            field=models.IntegerField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
