# Generated by Django 5.0.3 on 2024-03-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_producto_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='dni',
            field=models.IntegerField(unique=True),
        ),
    ]
